# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O9JMtuw-AiqU0dJjmTNa0zhJRYJf1SeG
"""

import pandas as pd
df = pd.read_csv("/content/python.csv")
df.head()

inputs = df.drop('Output',axis='columns')
target = df['Output']

target

from sklearn.preprocessing import LabelEncoder
le_sky = LabelEncoder()
le_Airtemp = LabelEncoder()
le_Humidity = LabelEncoder()
le_wind = LabelEncoder()
le_Forecast = LabelEncoder()

inputs['sky_n'] = le_sky.fit_transform(inputs['sky'])
inputs['Airtemp_n'] = le_Airtemp.fit_transform(inputs['Airtemp'])
inputs['Humidity_n'] = le_Humidity.fit_transform(inputs['Humidity'])
inputs['wind_n'] = le_wind.fit_transform(inputs['wind'])
inputs['Forecast_n'] = le_Forecast.fit_transform(inputs['Forecast'])

inputs

inputs_n = inputs.drop(['sky','Airtemp','Humidity','wind','water','Forecast'], axis ='columns')

inputs_n

from sklearn import tree
model = tree.DecisionTreeClassifier()

model.fit(inputs_n,target)

model.score(inputs_n,target)

model.predict([[1,1,1,0,1]])